// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using viajeroApi.Data;

#nullable disable

namespace viajeroApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107130056_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("viajeroApi.Model.Viagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_viagem");

                    b.Property<string>("AgenciaTransporte")
                        .HasColumnType("longtext")
                        .HasColumnName("agencia_transporte");

                    b.Property<string>("CodigoTransporte")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo_transporte");

                    b.Property<DateTime>("DataIda")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_ida");

                    b.Property<DateTime>("DataVolta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_volta");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<string>("Destino")
                        .HasColumnType("longtext")
                        .HasColumnName("destino");

                    b.Property<string>("EnderecoHospedagem")
                        .HasColumnType("longtext")
                        .HasColumnName("endereco_hospedagem");

                    b.Property<string>("GuiaTurismo")
                        .HasColumnType("longtext")
                        .HasColumnName("guiaTurismo");

                    b.Property<string>("Hospedagem")
                        .HasColumnType("longtext")
                        .HasColumnName("hospedagem");

                    b.Property<string>("Origem")
                        .HasColumnType("longtext")
                        .HasColumnName("origem");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("int")
                        .HasColumnName("qtd_pessoas");

                    b.Property<string>("TipoHospedagem")
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_hospedagem");

                    b.Property<string>("TipoViagem")
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_viagem");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_viagem");

                    b.HasKey("Id");

                    b.ToTable("Viagem");
                });
#pragma warning restore 612, 618
        }
    }
}
